[project]
name = "basic_locomotion_isaaclab_env"
version = "0.1.0"
channels = ["conda-forge", "nvidia", "robostack-staging"]
platforms = ["linux-64", "linux-aarch64"]

[dependencies]
python = "*"
pip = "*"
numpy = "*"
cuda-nvcc = "*"
ros-humble-desktop = "*"
ros-humble-rmw-cyclonedds-cpp = "*"
ros-humble-rosidl-generator-dds-idl = "*"
ros-humble-plotjuggler-ros = "*"
ros-humble-librealsense2 = "*"
ros-humble-realsense2-camera-msgs = "*"
ros-humble-realsense2-camera = "*"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
colcon-common-extensions = "*"
catkin_tools = "*"
rosdep = "*"
tqdm = "*"
gymnasium = "*"

[pypi-dependencies]
readchar = "*"
onnxruntime = "*"
torch = "*"
gym-quadruped = "*"
